# Generated by Django 6.0.5 on 2026-06-14 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='review_content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
