# Generated by Django 6.0.5 on 2026-06-20 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_product_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='productupdatereview',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
