# Generated by Django 6.0.5 on 2026-06-20 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_productupdatereview_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcreatereview',
            name='review_status',
            field=models.CharField(choices=[('P', 'Pending'), ('A', 'Approved'), ('R', 'Rejected'), ('AO', 'Admin Operated')], default='P', max_length=2),
        ),
        migrations.AlterField(
            model_name='productupdatereview',
            name='review_status',
            field=models.CharField(choices=[('P', 'Pending'), ('A', 'Approved'), ('R', 'Rejected'), ('AO', 'Admin Operated')], default='P', max_length=2),
        ),
    ]
