# Generated by Django 6.0.5 on 2026-06-20 20:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_alter_productcreatereview_review_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='productcreatereview',
            constraint=models.UniqueConstraint(fields=('proposed_name', 'proposed_price', 'review_status'), name='unique_proposed_name_proposed_price_review_status'),
        ),
    ]
