# Generated by Django 6.0.5 on 2026-06-20 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_productcreatereview_unique_proposed_name_proposed_price_review_status'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='productcreatereview',
            name='unique_proposed_name_proposed_price_review_status',
        ),
    ]
