# Generated by Django 6.0.5 on 2026-06-21 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_remove_productcreatereview_unique_proposed_name_proposed_price_review_status'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(fields=('name', 'price'), name='unique_product_name_price'),
        ),
    ]
